"""African echolocating bat species database.

Contains 100 African bat species with documented echolocation frequencies
from published research. Each entry includes taxonomic, acoustic, and
geographic information for use in bat call identification.

Geographic ranges:
  - Mainland Africa: lat -35 to 37, lon -20 to 52
  - Madagascar: lat -26 to -12, lon 43 to 51

Call categories:
  - CF: Constant-frequency calls (Rhinolophidae, Hipposideridae, Cloeotidae)
  - FM: Frequency-modulated calls (all other families)

Primary references:
  - Monadjem, A., Taylor, P.J., Cotterill, F.P.D. & Schoeman, M.C. (2010)
    Bats of Southern and Central Africa: A Biogeographic and Taxonomic Synthesis.
  - Taylor, P.J. (2000) Bats of Southern Africa.
  - Jacobs, D.S. et al. — various Rhinolophus and Hipposideros acoustic studies.
  - Ratrimomanarivo, F.H. et al. (2007) — Madagascar bat acoustic studies.
  - Schoeman, M.C. & Jacobs, D.S. (2008) — acoustic ecology of southern African bats.
  - Aldridge, D.J.N. & Rautenbach, I.L. (2003) — Tadarida and Chaerephon call libraries.
"""

# Geographic range constants
_AFRICA_MAINLAND = {"min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52}
_MADAGASCAR = {"min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51}

AFRICAN_SPECIES = [

    {
        "name": 'Cape horseshoe bat',
        "scientific": 'Rhinolophus capensis',
        "peak_freq_khz": 83.0,
        "freq_range": (80.0, 86.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Geoffroy's horseshoe bat",
        "scientific": 'Rhinolophus clivosus',
        "peak_freq_khz": 85.0,
        "freq_range": (82.0, 88.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Darling's horseshoe bat",
        "scientific": 'Rhinolophus darlingi',
        "peak_freq_khz": 88.0,
        "freq_range": (85.0, 91.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Hildebrandt's horseshoe bat",
        "scientific": 'Rhinolophus hildebrandtii',
        "peak_freq_khz": 58.0,
        "freq_range": (55.0, 61.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Blasius's horseshoe bat",
        "scientific": 'Rhinolophus blasii',
        "peak_freq_khz": 95.0,
        "freq_range": (92.0, 98.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Greater horseshoe bat',
        "scientific": 'Rhinolophus ferrumequinum',
        "peak_freq_khz": 78.0,
        "freq_range": (75.0, 81.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Lesser horseshoe bat',
        "scientific": 'Rhinolophus hipposideros',
        "peak_freq_khz": 113.0,
        "freq_range": (110.0, 116.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Lander's horseshoe bat",
        "scientific": 'Rhinolophus landeri',
        "peak_freq_khz": 95.0,
        "freq_range": (92.0, 98.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Halcyon horseshoe bat',
        "scientific": 'Rhinolophus alcyone',
        "peak_freq_khz": 85.0,
        "freq_range": (82.0, 88.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Guinea horseshoe bat',
        "scientific": 'Rhinolophus guineensis',
        "peak_freq_khz": 85.0,
        "freq_range": (82.0, 88.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Eloquent horseshoe bat',
        "scientific": 'Rhinolophus eloquens',
        "peak_freq_khz": 85.0,
        "freq_range": (82.0, 88.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Maclaud's horseshoe bat",
        "scientific": 'Rhinolophus maclaudi',
        "peak_freq_khz": 50.0,
        "freq_range": (47.0, 53.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Hill's horseshoe bat",
        "scientific": 'Rhinolophus hilli',
        "peak_freq_khz": 48.0,
        "freq_range": (45.0, 51.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Ruwenzori horseshoe bat',
        "scientific": 'Rhinolophus ruwenzorii',
        "peak_freq_khz": 48.0,
        "freq_range": (45.0, 51.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Bushveld horseshoe bat',
        "scientific": 'Rhinolophus simulator',
        "peak_freq_khz": 78.0,
        "freq_range": (75.0, 81.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Swinny's horseshoe bat",
        "scientific": 'Rhinolophus swinnyi',
        "peak_freq_khz": 108.0,
        "freq_range": (105.0, 111.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Dent's horseshoe bat",
        "scientific": 'Rhinolophus denti',
        "peak_freq_khz": 110.0,
        "freq_range": (107.0, 113.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Sakeji horseshoe bat',
        "scientific": 'Rhinolophus sakejiensis',
        "peak_freq_khz": 108.0,
        "freq_range": (105.0, 111.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Darling's-like horseshoe bat",
        "scientific": 'Rhinolophus cf. darlingi',
        "peak_freq_khz": 88.0,
        "freq_range": (85.0, 91.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Ruppell's horseshoe bat",
        "scientific": 'Rhinolophus fumigatus',
        "peak_freq_khz": 54.0,
        "freq_range": (51.0, 57.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Decken's horseshoe bat",
        "scientific": 'Rhinolophus deckenii',
        "peak_freq_khz": 100.0,
        "freq_range": (97.0, 103.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Forest horseshoe bat',
        "scientific": 'Rhinolophus silvestris',
        "peak_freq_khz": 92.0,
        "freq_range": (89.0, 95.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Mehely's horseshoe bat",
        "scientific": 'Rhinolophus mehelyi',
        "peak_freq_khz": 90.0,
        "freq_range": (87.0, 93.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Mediterranean horseshoe bat',
        "scientific": 'Rhinolophus euryale',
        "peak_freq_khz": 92.0,
        "freq_range": (89.0, 95.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Ethiopian horseshoe bat',
        "scientific": 'Rhinolophus monoceros',
        "peak_freq_khz": 95.0,
        "freq_range": (92.0, 98.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Maendeleo horseshoe bat',
        "scientific": 'Rhinolophus maendeleo',
        "peak_freq_khz": 78.0,
        "freq_range": (75.0, 81.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Mabu horseshoe bat',
        "scientific": 'Rhinolophus mabuensis',
        "peak_freq_khz": 85.0,
        "freq_range": (82.0, 88.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Rhodesian horseshoe bat',
        "scientific": 'Rhinolophus rhodesiae',
        "peak_freq_khz": 84.0,
        "freq_range": (81.0, 87.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Mozambican horseshoe bat',
        "scientific": 'Rhinolophus mossambicus',
        "peak_freq_khz": 33.0,
        "freq_range": (30.0, 36.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Cortioti's horseshoe bat",
        "scientific": 'Rhinolophus cortioti',
        "peak_freq_khz": 90.0,
        "freq_range": (87.0, 93.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Madagascar horseshoe bat',
        "scientific": 'Rhinolophus madagascariensis',
        "peak_freq_khz": 75.0,
        "freq_range": (72.0, 78.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": "Maclaud's horseshoe bat (Madagascar)",
        "scientific": 'Rhinolophus maclaudi madagascariensis',
        "peak_freq_khz": 50.0,
        "freq_range": (47.0, 53.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with brief FM sweeps',
        "call_category": 'CF',
        "family": 'Rhinolophidae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": 'Egyptian slit-faced bat',
        "scientific": 'Nycteris thebaica',
        "peak_freq_khz": 85.0,
        "freq_range": (80.0, 110.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Hairy slit-faced bat',
        "scientific": 'Nycteris hispida',
        "peak_freq_khz": 120.0,
        "freq_range": (115.0, 145.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Large-eared slit-faced bat',
        "scientific": 'Nycteris macrotis',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Dwarf slit-faced bat',
        "scientific": 'Nycteris nana',
        "peak_freq_khz": 115.0,
        "freq_range": (110.0, 140.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Large slit-faced bat',
        "scientific": 'Nycteris grandis',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Javan slit-faced bat',
        "scientific": 'Nycteris javanica',
        "peak_freq_khz": 120.0,
        "freq_range": (115.0, 145.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Gambian slit-faced bat',
        "scientific": 'Nycteris gambiensis',
        "peak_freq_khz": 85.0,
        "freq_range": (80.0, 110.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Bate's slit-faced bat",
        "scientific": 'Nycteris arge',
        "peak_freq_khz": 120.0,
        "freq_range": (115.0, 145.0),
        "call_type": 'FM',
        "rhythm": 'Short broadband FM, multiharmonic, gleaning',
        "call_category": 'FM',
        "family": 'Nycteridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Sundevall's roundleaf bat",
        "scientific": 'Hipposideros caffer',
        "peak_freq_khz": 142.0,
        "freq_range": (139.0, 145.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Noack's roundleaf bat",
        "scientific": 'Hipposideros ruber',
        "peak_freq_khz": 142.0,
        "freq_range": (139.0, 145.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Striped leaf-nosed bat',
        "scientific": 'Hipposideros vittatus',
        "peak_freq_khz": 58.0,
        "freq_range": (55.0, 61.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Commerson's leaf-nosed bat",
        "scientific": 'Hipposideros commersoni',
        "peak_freq_khz": 58.0,
        "freq_range": (55.0, 61.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Cyclops leaf-nosed bat',
        "scientific": 'Hipposideros cyclops',
        "peak_freq_khz": 58.0,
        "freq_range": (55.0, 61.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Sooty roundleaf bat',
        "scientific": 'Hipposideros fuliginosus',
        "peak_freq_khz": 142.0,
        "freq_range": (139.0, 145.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Giant leaf-nosed bat',
        "scientific": 'Macronycteris gigas',
        "peak_freq_khz": 58.0,
        "freq_range": (55.0, 61.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Striped leaf-nosed bat (Macronycteris)',
        "scientific": 'Macronycteris vittatus',
        "peak_freq_khz": 58.0,
        "freq_range": (55.0, 61.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Cameroon leaf-nosed bat',
        "scientific": 'Doryrhina camerunensis',
        "peak_freq_khz": 85.0,
        "freq_range": (82.0, 88.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Cyclops leaf-nosed bat (Doryrhina)',
        "scientific": 'Doryrhina cyclops',
        "peak_freq_khz": 58.0,
        "freq_range": (55.0, 61.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'African trident bat',
        "scientific": 'Triaenops afer',
        "peak_freq_khz": 75.0,
        "freq_range": (72.0, 78.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Red trident bat',
        "scientific": 'Triaenops rufus',
        "peak_freq_khz": 75.0,
        "freq_range": (72.0, 78.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Hipposideridae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": "Percival's trident bat",
        "scientific": 'Cloeotis percivali',
        "peak_freq_khz": 115.0,
        "freq_range": (112.0, 118.0),
        "call_type": 'CF-FM',
        "rhythm": 'Long-duration CF with FM sweep',
        "call_category": 'CF',
        "family": 'Cloeotidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Yellow-winged bat',
        "scientific": 'Lavia frons',
        "peak_freq_khz": 60.0,
        "freq_range": (55.0, 85.0),
        "call_type": 'FM',
        "rhythm": 'Short multiharmonic FM, low-intensity gleaning',
        "call_category": 'FM',
        "family": 'Megadermatidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Heart-nosed bat',
        "scientific": 'Cardioderma cor',
        "peak_freq_khz": 30.0,
        "freq_range": (25.0, 55.0),
        "call_type": 'FM',
        "rhythm": 'Short multiharmonic FM, low-intensity gleaning',
        "call_category": 'FM',
        "family": 'Megadermatidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Mauritian tomb bat',
        "scientific": 'Taphozous mauritianus',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'FM-QCF, regular interpulse intervals',
        "call_category": 'FM',
        "family": 'Emballonuridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Egyptian tomb bat',
        "scientific": 'Taphozous perforatus',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'FM-QCF, regular interpulse intervals',
        "call_category": 'FM',
        "family": 'Emballonuridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'African sheath-tailed bat',
        "scientific": 'Coleura afra',
        "peak_freq_khz": 35.0,
        "freq_range": (30.0, 60.0),
        "call_type": 'FM-QCF',
        "rhythm": 'FM-QCF, regular interpulse intervals',
        "call_category": 'FM',
        "family": 'Emballonuridae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Seychelles sheath-tailed bat',
        "scientific": 'Coleura seychellensis',
        "peak_freq_khz": 35.0,
        "freq_range": (30.0, 60.0),
        "call_type": 'FM-QCF',
        "rhythm": 'FM-QCF, regular interpulse intervals',
        "call_category": 'FM',
        "family": 'Emballonuridae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": "Bocage's myotis",
        "scientific": 'Myotis bocagii',
        "peak_freq_khz": 45.0,
        "freq_range": (40.0, 70.0),
        "call_type": 'FM',
        "rhythm": 'Steep broadband FM sweep',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Cape hairy bat',
        "scientific": 'Myotis tricolor',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep broadband FM sweep',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Ruppell's pipistrelle",
        "scientific": 'Pipistrellus rueppellii',
        "peak_freq_khz": 40.0,
        "freq_range": (35.0, 65.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Banana pipistrelle',
        "scientific": 'Pipistrellus nanus',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Dusky pipistrelle',
        "scientific": 'Pipistrellus hesperidus',
        "peak_freq_khz": 45.0,
        "freq_range": (40.0, 70.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Cape serotine',
        "scientific": 'Neoromicia capensis',
        "peak_freq_khz": 35.0,
        "freq_range": (30.0, 60.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Banana serotine',
        "scientific": 'Neoromicia nana',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Somali serotine',
        "scientific": 'Neoromicia somalica',
        "peak_freq_khz": 45.0,
        "freq_range": (40.0, 70.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Zulu serotine',
        "scientific": 'Neoromicia zuluensis',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Schlieffen's bat",
        "scientific": 'Nycticeius schlieffenii',
        "peak_freq_khz": 35.0,
        "freq_range": (30.0, 60.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, short duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Yellow-bellied house bat',
        "scientific": 'Scotophilus dinganii',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF component',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'White-bellied house bat',
        "scientific": 'Scotophilus leucogaster',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF component',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Green house bat',
        "scientific": 'Scotophilus viridis',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF component',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Reunion yellow bat',
        "scientific": 'Scotophilus borbonicus',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF component',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": 'Botswana long-eared bat',
        "scientific": 'Laephotis botswanae',
        "peak_freq_khz": 35.0,
        "freq_range": (30.0, 60.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, slow-flying approach',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Namibian long-eared bat',
        "scientific": 'Laephotis namibensis',
        "peak_freq_khz": 35.0,
        "freq_range": (30.0, 60.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, slow-flying approach',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Angolan long-eared bat',
        "scientific": 'Laephotis angolensis',
        "peak_freq_khz": 35.0,
        "freq_range": (30.0, 60.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, slow-flying approach',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Hottentot serotine',
        "scientific": 'Eptesicus hottentotus',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, moderate duration',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Schreibers's long-fingered bat",
        "scientific": 'Miniopterus schreibersii',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, often in pairs',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Natal long-fingered bat',
        "scientific": 'Miniopterus natalensis',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, often in pairs',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Lesser long-fingered bat',
        "scientific": 'Miniopterus fraterculus',
        "peak_freq_khz": 55.0,
        "freq_range": (50.0, 80.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, often in pairs',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Greater long-fingered bat',
        "scientific": 'Miniopterus inflatus',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, often in pairs',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Minor long-fingered bat',
        "scientific": 'Miniopterus minor',
        "peak_freq_khz": 60.0,
        "freq_range": (55.0, 85.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, often in pairs',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Mozambique long-fingered bat',
        "scientific": 'Miniopterus mossambicus',
        "peak_freq_khz": 60.0,
        "freq_range": (55.0, 85.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, often in pairs',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Mahafaly long-fingered bat',
        "scientific": 'Miniopterus mahafaliensis',
        "peak_freq_khz": 50.0,
        "freq_range": (45.0, 75.0),
        "call_type": 'FM',
        "rhythm": 'Steep FM sweep, often in pairs',
        "call_category": 'FM',
        "family": 'Vespertilionidae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": 'Egyptian free-tailed bat',
        "scientific": 'Tadarida aegyptiaca',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, fast-flight search calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Madagascan large free-tailed bat',
        "scientific": 'Tadarida fulminans',
        "peak_freq_khz": 20.0,
        "freq_range": (15.0, 45.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, fast-flight search calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Big-eared free-tailed bat',
        "scientific": 'Tadarida lobata',
        "peak_freq_khz": 15.0,
        "freq_range": (10.0, 40.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, fast-flight search calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Little free-tailed bat',
        "scientific": 'Chaerephon pumilus',
        "peak_freq_khz": 30.0,
        "freq_range": (25.0, 55.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, fast-flight search calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Midas free-tailed bat',
        "scientific": 'Chaerephon midas',
        "peak_freq_khz": 20.0,
        "freq_range": (15.0, 45.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, fast-flight search calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Angolan free-tailed bat',
        "scientific": 'Mops condylurus',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, search-phase calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Midas free-tailed bat (Mops)',
        "scientific": 'Mops midas',
        "peak_freq_khz": 20.0,
        "freq_range": (15.0, 45.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, search-phase calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'White-bellied free-tailed bat',
        "scientific": 'Mops niveiventris',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, search-phase calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Trevor's free-tailed bat",
        "scientific": 'Mops trevori',
        "peak_freq_khz": 20.0,
        "freq_range": (15.0, 45.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, search-phase calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": "Martienssen's free-tailed bat",
        "scientific": 'Otomops martiensseni',
        "peak_freq_khz": 15.0,
        "freq_range": (10.0, 40.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Low-frequency FM-QCF, fast high-altitude flight',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Madagascar free-tailed bat',
        "scientific": 'Otomops madagascariensis',
        "peak_freq_khz": 15.0,
        "freq_range": (10.0, 40.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Low-frequency FM-QCF, fast high-altitude flight',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": 'Rock-dwelling free-tailed bat',
        "scientific": 'Sauromys petrophilus',
        "peak_freq_khz": 30.0,
        "freq_range": (25.0, 55.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, rock-crevice foraging',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Malagasy free-tailed bat',
        "scientific": 'Mormopterus jugularis',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, search-phase calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -26, "max_lat": -12, "min_lon": 43, "max_lon": 51,
        "continents": ["Africa"],
    },
    {
        "name": 'European free-tailed bat',
        "scientific": 'Tadarida teniotis',
        "peak_freq_khz": 12.0,
        "freq_range": (10.0, 37.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, fast-flight search calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Nigerian free-tailed bat',
        "scientific": 'Chaerephon nigeriae',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, fast-flight search calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
    {
        "name": 'Sierra Leone free-tailed bat',
        "scientific": 'Mops brachypterus',
        "peak_freq_khz": 25.0,
        "freq_range": (20.0, 50.0),
        "call_type": 'FM-QCF',
        "rhythm": 'Shallow FM with QCF tail, search-phase calls',
        "call_category": 'FM',
        "family": 'Molossidae',
        "min_lat": -35, "max_lat": 37, "min_lon": -20, "max_lon": 52,
        "continents": ["Africa"],
    },
]

if __name__ == "__main__":
    print(f"AFRICAN_SPECIES contains {len(AFRICAN_SPECIES)} species")
    _required = {
        "name", "scientific", "peak_freq_khz", "freq_range",
        "call_type", "rhythm", "call_category", "family",
        "min_lat", "max_lat", "min_lon", "max_lon", "continents",
    }
    _families = {}
    _categories = {}
    for i, s in enumerate(AFRICAN_SPECIES):
        missing = _required - set(s.keys())
        if missing:
            print(f"  ERROR entry {i} ({s.get('scientific', '?')}): missing {missing}")
        _families[s["family"]] = _families.get(s["family"], 0) + 1
        _categories[s["call_category"]] = _categories.get(s["call_category"], 0) + 1
    print(f"  Families: {_families}")
    print(f"  Categories: {_categories}")
    print("Validation complete.")
