"""
North American Bat Species Database.

49 echolocating bat species from North America (USA, Canada, Mexico, Central America).
Data sourced from SonoBat acoustic tables (Western & Eastern NA), NABat/USGS,
Bat Conservation International, and published academic papers.

Families covered:
  - Vespertilionidae (31): Myotis, Eptesicus, Lasiurus, Lasionycteris, Nycticeius,
    Perimyotis, Parastrellus, Corynorhinus, Antrozous, Idionycteris, Euderma
  - Molossidae (8): Tadarida, Eumops, Nyctinomops
  - Mormoopidae (6): Pteronotus, Mormoops
  - Phyllostomidae (4): Macrotus, Choeroniscus, Leptonycteris

Frequency range: 8 kHz (Euderma maculatum) to 75 kHz (Myotis californicus)
"""


NORTH_AMERICAN_SPECIES = [
    {"name": "Yuma Myotis", "scientific": "Myotis yumanensis", "peak_freq_khz": 51.2, "freq_range": (42.5, 57.5), "call_type": "FM sweep, smooth curve, pronounced knee", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "California Myotis", "scientific": "Myotis californicus", "peak_freq_khz": 49.5, "freq_range": (41.5, 55.5), "call_type": "FM sweep, smooth curve with downward tail", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Southeastern Myotis", "scientific": "Myotis austroriparius", "peak_freq_khz": 44.0, "freq_range": (39, 58), "call_type": "FM sweep, smooth curve, downward tail", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Gray Myotis", "scientific": "Myotis grisescens", "peak_freq_khz": 46.3, "freq_range": (40, 52), "call_type": "FM sweep with strong inflection at knee, pronounced tail", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Eastern Small-footed Myotis", "scientific": "Myotis leibii", "peak_freq_khz": 44.3, "freq_range": (38, 48), "call_type": "FM sweep, smooth curve, forages close to ground", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Western Small-footed Myotis", "scientific": "Myotis ciliolabrum", "peak_freq_khz": 42.7, "freq_range": (37.5, 49), "call_type": "FM sweep, smooth curve, downward tail", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Indiana Myotis", "scientific": "Myotis sodalis", "peak_freq_khz": 42.3, "freq_range": (37, 55), "call_type": "FM sweep, long call type with secondary inflection", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Little Brown Myotis", "scientific": "Myotis lucifugus", "peak_freq_khz": 42.0, "freq_range": (35, 50), "call_type": "FM sweep, long duration with curved knee, low slope body", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Northern Long-eared Myotis", "scientific": "Myotis septentrionalis", "peak_freq_khz": 43.3, "freq_range": (36, 56), "call_type": "FM sweep, nearly linear, up to 100 kHz bandwidth, quiet calls", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Long-legged Myotis", "scientific": "Myotis volans", "peak_freq_khz": 42.7, "freq_range": (34, 50.5), "call_type": "FM sweep, steeper body than other 40kHz myotis, may have upward sweep", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Fringed Myotis", "scientific": "Myotis thysanodes", "peak_freq_khz": 25.6, "freq_range": (21, 31.5), "call_type": "FM sweep, nearly linear, up to 100 kHz bandwidth", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Long-eared Myotis", "scientific": "Myotis evotis", "peak_freq_khz": 36.0, "freq_range": (29, 42.5), "call_type": "FM sweep, nearly linear, up to 100 kHz bandwidth, quiet", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Cave Myotis", "scientific": "Myotis velifer", "peak_freq_khz": 40.0, "freq_range": (34, 49), "call_type": "FM sweep, smooth curve, less-defined downward tail", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Southwestern Myotis", "scientific": "Myotis auriculus", "peak_freq_khz": 40.6, "freq_range": (31.5, 52.5), "call_type": "FM sweep, steeper body, long toes", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Big Brown Bat", "scientific": "Eptesicus fuscus", "peak_freq_khz": 28.2, "freq_range": (22, 35.5), "call_type": "FM sweep, variable, may hook upward at end", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Silver-haired Bat", "scientific": "Lasionycteris noctivagans", "peak_freq_khz": 26.5, "freq_range": (22, 32), "call_type": "FM to flat, hockey-stick shaped, distinct inflection", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Eastern Red Bat", "scientific": "Lasiurus borealis", "peak_freq_khz": 41.2, "freq_range": (29, 56), "call_type": "U-shaped or reverse-J, upturn at end, variable fc", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Hoary Bat", "scientific": "Lasiurus cinereus", "peak_freq_khz": 21.7, "freq_range": (15, 36), "call_type": "Pronounced U-shape, very flat, variable fc, low bandwidth", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Seminole Bat", "scientific": "Lasiurus seminolus", "peak_freq_khz": 40.4, "freq_range": (29, 55), "call_type": "U-shaped, upturn at end, variable fc, similar to Eastern Red", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Western Red Bat", "scientific": "Lasiurus blossevillii", "peak_freq_khz": 43.4, "freq_range": (36.5, 54), "call_type": "U-shaped, upturn at end, variable fc and duration", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Northern Yellow Bat", "scientific": "Lasiurus intermedius", "peak_freq_khz": 31.4, "freq_range": (23, 40), "call_type": "U-shaped, upturn at end, variable fc, intermediate frequency", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Western Yellow Bat", "scientific": "Lasiurus xanthinus", "peak_freq_khz": 33.6, "freq_range": (26, 40), "call_type": "U-shaped, upturn at end, variable fc, dur>10 diagnostic", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Southern Yellow Bat", "scientific": "Lasiurus ega", "peak_freq_khz": 29.0, "freq_range": (23, 40), "call_type": "U-shaped, upturn at end, variable fc, low frequency caller", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Evening Bat", "scientific": "Nycticeius humeralis", "peak_freq_khz": 38.0, "freq_range": (32, 46), "call_type": "Curved FM sweep, fc below 40kHz, may alternate fc up/down", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Tricolored Bat", "scientific": "Perimyotis subflavus", "peak_freq_khz": 43.3, "freq_range": (36, 50), "call_type": "Strongly inflected FM, hockey-stick shaped, consistent across sequence", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Canyon Bat", "scientific": "Parastrellus hesperus", "peak_freq_khz": 46.1, "freq_range": (41, 51.5), "call_type": "Strongly inflected FM, hockey-stick shaped, squiggles", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Pallid Bat", "scientific": "Antrozous pallidus", "peak_freq_khz": 27.1, "freq_range": (24, 33.5), "call_type": "Simple curved FM, sometimes dog-paw ledge, distinctive social calls", "rhythm": "irregular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Townsend's Big-eared Bat", "scientific": "Corynorhinus townsendii", "peak_freq_khz": 28.0, "freq_range": (18, 31), "call_type": "Simple linear FM sweep, low intensity, harmonics often present", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Rafinesque's Big-eared Bat", "scientific": "Corynorhinus rafinesquii", "peak_freq_khz": 28.0, "freq_range": (19, 38), "call_type": "Simple linear FM sweep, low intensity, harmonics present", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Allen's Big-eared Bat", "scientific": "Idionycteris phyllotis", "peak_freq_khz": 12.9, "freq_range": (8.5, 18), "call_type": "Bi-linear FM sweep, 25kHz down to 11-13kHz, harmonics often present", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Spotted Bat", "scientific": "Euderma maculatum", "peak_freq_khz": 9.3, "freq_range": (7.2, 12), "call_type": "Simple linear FM sweep, audible to humans, 12-6kHz fundamental", "rhythm": "regular", "call_category": "FM", "family": "Vespertilionidae", "min_lat": 7, "max_lat": 70, "min_lon": -168, "max_lon": -60, "continents": ['North America']},
    {"name": "Brazilian Free-tailed Bat", "scientific": "Tadarida brasiliensis", "peak_freq_khz": 24.7, "freq_range": (15, 39), "call_type": "Variable FM to flat, upswing into call, downswing out, carrot-shaped oscillogram", "rhythm": "irregular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Pocketed Free-tailed Bat", "scientific": "Nyctinomops femorosaccus", "peak_freq_khz": 19.9, "freq_range": (14, 28), "call_type": "FM to flat, upswing into call, downswing out, intermediate fc", "rhythm": "irregular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Big Free-tailed Bat", "scientific": "Nyctinomops macrotis", "peak_freq_khz": 12.7, "freq_range": (10, 15), "call_type": "Low frequency QCF, upswing into call, audible to humans", "rhythm": "irregular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Broad-eared Free-tailed Bat", "scientific": "Nyctinomops laticaudatus", "peak_freq_khz": 28.7, "freq_range": (25, 33), "call_type": "QCF with downward modulation, alternates among 3 frequencies", "rhythm": "regular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Wagner's Bonneted Bat", "scientific": "Eumops glaucinus", "peak_freq_khz": 22.0, "freq_range": (15, 25), "call_type": "Low frequency FM, long duration, narrow bandwidth, below 20-25kHz", "rhythm": "regular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Western Mastiff Bat", "scientific": "Eumops perotis", "peak_freq_khz": 10.7, "freq_range": (7, 15.5), "call_type": "QCF to FM, long low sweeps, audible to humans, lowest frequency NA bat", "rhythm": "regular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Florida Bonneted Bat", "scientific": "Eumops floridanus", "peak_freq_khz": 14.6, "freq_range": (10, 21), "call_type": "Simple sweeps with slight curvature, long low calls, partially audible", "rhythm": "regular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Underwood's Bonneted Bat", "scientific": "Eumops underwoodi", "peak_freq_khz": 12.0, "freq_range": (10, 14), "call_type": "Low frequency, long duration, narrow bandwidth QCF", "rhythm": "regular", "call_category": "FM", "family": "Molossidae", "min_lat": 8, "max_lat": 50, "min_lon": -125, "max_lon": -70, "continents": ['North America', 'South America']},
    {"name": "Ghost-faced Bat", "scientific": "Mormoops megalophylla", "peak_freq_khz": 50.0, "freq_range": (40, 60), "call_type": "Short FM sweep, multiharmonic, quasi-CF component, prominent 2nd harmonic", "rhythm": "regular", "call_category": "FM", "family": "Mormoopidae", "min_lat": 8, "max_lat": 33, "min_lon": -110, "max_lon": -75, "continents": ['North America', 'South America']},
    {"name": "Parnell's Mustached Bat", "scientific": "Pteronotus parnellii", "peak_freq_khz": 61.5, "freq_range": (54, 65), "call_type": "Long CF-FM, 4-5 harmonics, CF2 at 61kHz dominant, Doppler-shift compensation", "rhythm": "regular", "call_category": "CF", "family": "Mormoopidae", "min_lat": 8, "max_lat": 33, "min_lon": -110, "max_lon": -75, "continents": ['North America', 'South America']},
    {"name": "Wagner's Mustached Bat", "scientific": "Pteronotus personatus", "peak_freq_khz": 83.0, "freq_range": (68, 90), "call_type": "Short CF-FM, two CF components separated by FM, dominant 2nd harmonic", "rhythm": "regular", "call_category": "CF", "family": "Mormoopidae", "min_lat": 8, "max_lat": 33, "min_lon": -110, "max_lon": -75, "continents": ['North America', 'South America']},
    {"name": "Davy's Mustached Bat", "scientific": "Pteronotus davyi", "peak_freq_khz": 68.1, "freq_range": (55, 72), "call_type": "Short CF-FM, initial CF then FM sweep to terminal CF, 2nd harmonic dominant", "rhythm": "regular", "call_category": "CF", "family": "Mormoopidae", "min_lat": 8, "max_lat": 33, "min_lon": -110, "max_lon": -75, "continents": ['North America', 'South America']},
    {"name": "Macleay's Mustached Bat", "scientific": "Pteronotus macleayii", "peak_freq_khz": 70.0, "freq_range": (67, 73), "call_type": "Short CF-FM, 4 harmonics, 2nd harmonic dominant at 70kHz", "rhythm": "regular", "call_category": "CF", "family": "Mormoopidae", "min_lat": 8, "max_lat": 33, "min_lon": -110, "max_lon": -75, "continents": ['North America', 'South America']},
    {"name": "Sooty Mustached Bat", "scientific": "Pteronotus quadridens", "peak_freq_khz": 83.3, "freq_range": (79, 87), "call_type": "Short CF-FM, 3 non-overlapping harmonics, 2nd harmonic loudest", "rhythm": "regular", "call_category": "CF", "family": "Mormoopidae", "min_lat": 8, "max_lat": 33, "min_lon": -110, "max_lon": -75, "continents": ['North America', 'South America']},
    {"name": "California Leaf-nosed Bat", "scientific": "Macrotus californicus", "peak_freq_khz": 56.9, "freq_range": (46, 66), "call_type": "Gently curving S-shaped FM, multiharmonic, power in 1st harmonic", "rhythm": "regular", "call_category": "FM", "family": "Phyllostomidae", "min_lat": 8, "max_lat": 38, "min_lon": -117, "max_lon": -80, "continents": ['North America', 'South America']},
    {"name": "Mexican Long-tongued Bat", "scientific": "Choeronycteris mexicana", "peak_freq_khz": 44.2, "freq_range": (31.5, 51.5), "call_type": "Gently curving S-shaped FM, multiharmonic, nectar feeder that echolocates", "rhythm": "regular", "call_category": "FM", "family": "Phyllostomidae", "min_lat": 8, "max_lat": 38, "min_lon": -117, "max_lon": -80, "continents": ['North America', 'South America']},
    {"name": "Lesser Long-nosed Bat", "scientific": "Leptonycteris yerbabuenae", "peak_freq_khz": 38.6, "freq_range": (29, 43), "call_type": "Gently curving S-shaped FM, multiharmonic, short FM search calls", "rhythm": "regular", "call_category": "FM", "family": "Phyllostomidae", "min_lat": 8, "max_lat": 38, "min_lon": -117, "max_lon": -80, "continents": ['North America', 'South America']},
    {"name": "Greater Long-nosed Bat", "scientific": "Leptonycteris nivalis", "peak_freq_khz": 38.0, "freq_range": (29, 45), "call_type": "Gently curving S-shaped FM, multiharmonic, nectar feeder", "rhythm": "regular", "call_category": "FM", "family": "Phyllostomidae", "min_lat": 8, "max_lat": 38, "min_lon": -117, "max_lon": -80, "continents": ['North America', 'South America']},
]